config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end

    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end

  end

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :set_mining_type_options, only: [:new, :edit, :update, :create]


  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_img, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: [:show, :edit, :update, :destroy]

  # GET /mining_types
  # GET /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1
  # GET /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types
  # POST /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1
  # PATCH/PUT /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1
  # DELETE /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso de Ruby On Rails - [COOKIE]"
    session[:curso] = "Curso de Ruby On Rails - [SESSION]"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_br(data_us)
    data_us.strftime("%d/%m/%Y")
  end

  def nome_aplicacao
    "Crypto Wallet"
  end

  def ambiente_rails
    if Rails.env.development?
      "Desenvolvimento"
    elsif Rails.env.production?
      "Produção"
    else
      "Teste"
    end
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>

  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Descrição" %>
    <%= form.text_field :description, class:"form-control", placeholder:"Informe a Descrição" %>
  </div>

  <div class="form-group">
    <%= form.label "Acrônimo" %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"Informe o Acrônimo"%>
  </div>

  <div class="form-group">
    <%= form.label "Localização da Imagem" %>
    <%= form.text_field :url_img, size:50, class:"form-control", placeholder:"Informe a localização da Imagem" %>
  </div>

  <div class="form-group">
    <%= form.label "Tipo de Mineração" %>
    <%= form.select("mining_type_id", @mining_type_options , {include_blank: "Selecione ..."}, class:"form-control") %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>

<% end %>

app/views/coins/edit.html.erb
<h1>Editando Moedas</h1>

<%= render 'form', coin: @coin %>

<br/>

<%= link_to 'Exibir', @coin, class:"btn btn-primary" %> |
<%= link_to 'Voltar', coins_path, class:"btn btn-primary" %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coins</h1>


<table class="table">
  <thead>
    <tr>
      <th>Moeda</th>
      <th>Sigla</th>
      <th>Imagem</th>
      <th>Criado em</th>
      <th>Atualizado em</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td>
           <%= image_tag coin.url_img, width:"25px", heigth:"25px"  %>
        </td>
        <td><%= l coin.created_at %></td>
        <td><%= l coin.updated_at %></td>

        <td><%= link_to 'Exibir', coin %></td>
        <td><%= link_to 'Editar', edit_coin_path(coin) %></td>
        <td><%= link_to 'Excluir', coin, method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Moeda', new_coin_path, class:"btn btn-primary" %>

app/views/coins/new.html.erb
<h1>Nova Moeda</h1>

<%= render 'form', coin: @coin %>

<br/>
<%= link_to 'Voltar', coins_path, class:"btn btn-primary" %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>


<form>

  <div class="form-group">
    <%= label_tag nil, "Descrição" %>
    <%= text_field_tag nil, @coin.description, class:"form-control", disabled:true%>
  </div>

  <div class="form-group">
    <%= label_tag nil, "Acrônimo" %>
    <%= text_field_tag nil, @coin.acronym, class:"form-control", disabled:true %>
  </div>

  <div class="form-group">
      <%= label_tag nil, "Localização da Imagem" %>
      <%= text_field_tag nil, @coin.url_img, size:50, class:"form-control", disabled:true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, "Tipo de Mineração" %>
    <%= text_field_tag nil, @coin.mining_type.description, class:"form-control", disabled:true %>
  </div>

</form>

<%= link_to 'Edit', edit_coin_path(@coin) , class:"btn btn-primary"%> |
<%= link_to 'Back', coins_path, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
     <div class="container-fluid">
        <ul class="nav justify-content-end">
          <li>
            <%= link_to  "[HOME]", root_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to  "Português", root_path(locale: 'pt-BR'), class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to  "English", root_path(locale: 'en'), class:"nav-link active" %>
          </li>
      </ul>

      <%= yield %>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Descrição" %>
    <%= form.text_field :description, class:"form-control", placeholder:"Informe a Descrição" %>
  </div>

  <div class="form-group">
    <%= form.label "Acrônimo" %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"Informe o Acrônimo" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1>Editing Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<br/>

<%= link_to 'Show', @mining_type, class:"btn btn-primary" %> |
<%= link_to 'Back', mining_types_path, class:"btn btn-primary" %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mining Types</h1>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to 'Mostrar', mining_type %></td>
        <td><%= link_to 'Editar', edit_mining_type_path(mining_type) %></td>
        <td><%= link_to 'Excluir', mining_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Tipo de Mineração', new_mining_type_path, class:"btn btn-primary" %>

app/views/mining_types/new.html.erb
<h1>Tipos de Mineração</h1>

<%= render 'form', mining_type: @mining_type %>

<br/>
<%= link_to 'Voltar', mining_types_path, class:"btn btn-primary" %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<form>

<div class="form-group">
  <%= label_tag nil, "Descrição" %>
  <%= text_field_tag nil, @mining_type.description, class:"form-control", disabled:true %>
</div>

<div class="form-group">
  <%= label_tag nil, "Acrônimo" %>
  <%= text_field_tag nil, @mining_type.acronym, class:"form-control", disabled:true %>

</div>

</form>

<%= link_to 'Edit', edit_mining_type_path(@mining_type), class:"btn btn-primary"%> |
<%= link_to 'Back', mining_types_path, class:"btn btn-primary" %>

app/views/welcome/_menu.html.erb
<%= link_to  "Cadastro de Moedas", coins_path, class: "btn btn-primary btn-lg", role: "button" %>
<%= link_to  "Tipos de Mineração", mining_types_path, class: "btn btn-primary btn-lg", role: "button" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Seja Bem-vindo !!!</h1>
  <p class="lead">Este é o Crypto Wallet, uma app para você cadastrar e acompanhar as suas cryptomoedas.</p>
  <hr class="my-4">
  <p>Para começar selecione umas das opções abaixo:</p>
  <%= render "menu" %>
</div>